# Generated by Django 5.1.2 on 2025-01-27 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('chest_pain_type', models.CharField(choices=[('TA', 'Typical Angina'), ('ATA', 'Atypical Angina'), ('NAP', 'Non-Anginal Pain'), ('ASY', 'Asymptomatic')], max_length=4)),
                ('resting_bp', models.PositiveIntegerField()),
                ('cholesterol', models.PositiveIntegerField()),
                ('fasting_bs', models.BooleanField()),
                ('resting_ecg', models.CharField(choices=[('Normal', 'Normal'), ('ST', 'ST-T Wave Abnormality'), ('LVH', 'Left Ventricular Hypertrophy')], max_length=10)),
                ('max_hr', models.PositiveIntegerField()),
                ('exercise_angina', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('oldpeak', models.DecimalField(decimal_places=1, max_digits=4)),
                ('st_slope', models.CharField(choices=[('Up', 'Upsloping'), ('Flat', 'Flat'), ('Down', 'Downsloping')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
