# Generated by Django 5.1.2 on 2025-01-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='chest_pain_type',
            new_name='Chest_Pain_Type',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='fasting_bs',
            new_name='fastingBS',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='max_hr',
            new_name='maxHR',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='resting_bp',
            new_name='restingBP',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='resting_ecg',
            new_name='restingECG',
        ),
    ]
