# Generated by Django 5.1.2 on 2025-01-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_system', '0002_rename_chest_pain_type_assessment_chest_pain_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='fastingBS',
            field=models.CharField(choices=[('Less than 120', 'Less than 120mg/dL'), ('Greater than 120', 'Greater than 120mg/dL')], max_length=20),
        ),
    ]
