# Generated by Django 5.1.2 on 2025-01-28 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_system', '0004_assessment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
