# Generated by Django 5.1.2 on 2025-01-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_system', '0005_assessment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
